adjust ermrest-registry-purge to tolerate alias entries in registry
Normally, dead aliases should be deleted by the service, but if a DBA
intervenes or if this tool is run to purge ALL records, it can
encounter an alias record that it should delete. However, aliases do
not have a descriptor and so the tool should skip db-related cleanup
for those records.

diff --git a/sbin/ermrest-registry-purge b/sbin/ermrest-registry-purge
--- a/sbin/ermrest-registry-purge
+++ b/sbin/ermrest-registry-purge
@@ -113,8 +113,10 @@ do
         continue
     fi
 
+    # NOTE: empty string "$db" means we found an alias to delete
+    
     # force disconnect of clients, optional
-    if [ -n "${FORCE}" ]; then
+    if [ -n "$db" -a -n "${FORCE}" ]; then
         psql -q "${ERMREST}" >/dev/null <<EOF
 SELECT pid, (SELECT pg_terminate_backend(pid)) as killed
 FROM pg_stat_activity
@@ -128,7 +130,7 @@ EOF
     fi
 
     # dump database to archive directory before purge, optional
-    if [ -n "${ARCHIVE}" ]; then
+    if [ -n "$db" -a -n "${ARCHIVE}" ]; then
         filename="${ARCHIVE}/${id}-${db}-`date +%s`.sql"
         pg_dump --blobs --no-owner "${db}" >"${filename}"
         if [ $? -eq 0 -a -s "${filename}" ]; then
@@ -142,12 +144,15 @@ EOF
     fi
 
     # drop database
-    dropdb --if-exists "${db}"
-    if [ $? -ne 0 ]; then
-        log " DROP FAILED\n"
-        continue
+    if [[ -n "$db" ]]
+    then
+        dropdb --if-exists "${db}"
+        if [ $? -ne 0 ]; then
+            log " DROP FAILED\n"
+            continue
+        fi
+        log " DROPPED"
     fi
-    log " DROPPED"
 
     # delete registry entry of catalog
     psql -q -c "DELETE FROM ermrest.simple_registry WHERE id = '${id}'" ${ERMREST}
